# Generated by Django 5.0.3 on 2024-03-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_app', '0002_alter_sugarlevellist_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugarlevelmeasure',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sugarlevelmeasure',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sugarlevelmeasure',
            name='fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sugarlevelmeasure',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sugarlevelmeasure',
            name='proteins',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
