# Generated by Django 5.0.3 on 2024-03-22 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_app', '0002_alter_user_birth_alter_user_height_alter_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugarlevellist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
