# Generated by Django 5.0.3 on 2024-03-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_app', '0003_alter_sugarlevelmeasure_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugarlevelmeasure',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sugarlevelmeasure',
            name='time',
            field=models.TimeField(),
        ),
    ]
