# Generated by Django 5.0.3 on 2024-03-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_app', '0003_alter_sugarlevellist_user_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
