# Generated by Django 5.0.3 on 2024-03-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_app', '0004_alter_sugarlevelmeasure_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='dose',
            field=models.CharField(blank=True, null=True),
        ),
    ]
