# Generated by Django 4.2.11 on 2024-04-03 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_app', '0007_remove_user_registration_method_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=datetime.datetime(2024, 4, 3, 7, 59, 47, 186972, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
